### ISSUE TITLE
Call to undefined method FeatureContext::getSession() if not extending MinkContext

### ISSUE THREAD

**Issue by hackel** [laracasts/Behat-Laravel-Extension#23]
The documentation makes it sound as if extending Behat\MinkExtension\Context\MinkContext is optional, however without it, I get this error:

``` ObjDump
PHP Fatal error:  Call to undefined method MyApp\FeatureContext::getSession() in ./vendor/laracasts/behat-laravel-extension/src/Context/KernelAwareInitializer.php on line 78
Stack trace:
#1. {main}() ./vendor/behat/behat/bin/behat:0
#2. Symfony\Component\Console\Application->run() ./vendor/behat/behat/bin/behat:31
#3. Behat\Testwork\Cli\Application->doRun() ./vendor/symfony/console/Symfony/Component/Console/Application.php:126
#4. Symfony\Component\Console\Application->doRun() ./vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:102
#5. Symfony\Component\Console\Application->doRunCommand() ./vendor/symfony/console/Symfony/Component/Console/Application.php:195
#6. Symfony\Component\Console\Command\Command->run() ./vendor/symfony/console/Symfony/Component/Console/Application.php:874
#7. Behat\Testwork\Cli\Command->execute() ./vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
#8. Behat\Testwork\Tester\Cli\ExerciseController->execute() ./vendor/behat/behat/src/Behat/Testwork/Cli/Command.php:63
#9. Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications() ./vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:108
#10. Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test() ./vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:146
#11. Behat\Testwork\Tester\Runtime\RuntimeExercise->test() ./vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php:70
#12. Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test() ./vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php:71
#13. Behat\Testwork\Hook\Tester\HookableSuiteTester->test() ./vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php:72
#14. Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test() ./vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php:73
#15. Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test() ./vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php:63
#16. Behat\Behat\Hook\Tester\HookableFeatureTester->test() ./vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php:71
#17. Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test() ./vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php:72
#18. Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->tearDown() ./vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php:84
#19. Behat\Testwork\EventDispatcher\TestworkEventDispatcher->dispatch() ./vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php:117
#20. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() ./vendor/behat/behat/src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php:39
#21. call_user_func:{./vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164}() ./vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
#22. Laracasts\Behat\Context\KernelAwareInitializer->rebootKernel() ./vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164

PHP Fatal error:  Uncaught exception 'Illuminate\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in ./vendor/laravel/framework/src/Illuminate/Container/Container.php:785
Stack trace:
#0 ./vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 ./vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 ./vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(151): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 ./vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(73): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#4 /home/hackel/d in ./vendor/laravel/framework/src/Illuminate/Container/Container.php on line 785
```

Of course I do plan to use MinkContext, I just thought I would point out this current discrepancy.

**Comment by revati** [comment]
The same here

**Comment by jossemarGT** [comment]
Sorry to bother but... Same here

**Comment by jossemarGT** [comment]
Nvm... I found the answer right in the [comments](https://laracasts.com/lessons/laravel-5-and-behat-bffs#comment-1813612970) "Figured it out. Forgot to extend MinkContext."

Cheers :octocat:

**Comment by alnutile** [comment]
Updating docs to make this more clear. https://github.com/laracasts/Behat-Laravel-Extension/compare/master...alnutile-feature-context?quick_pull=1

**Comment by alnutile** [comment]
Updated docs going to close this feel free to reopen if needed.
